---
kind: pipeline
type: kubernetes
name: build
steps:
- name: build
  image: docker.io/oven/bun:1
  commands:
  - bun install
  - bun run build
- name: image
  image: images.home.mtaylor.io/drone-kaniko:latest
  settings:
    repo: images.home.mtaylor.io/mtaylor.io
    auto_tag: true
    enable_cache: true
    username: anonymous
    password: anonymous
    registry: images.home.mtaylor.io
- name: deploy
  image: images.home.mtaylor.io/deployer:0.0.7
  commands:
  - set -u
  - pwd
  - whoami
  - mkdir -p ~/.ssh
  - echo -n "$SSH_KEY_BASE64" | base64 --decode > ~/.ssh/id_ed25519
  - chmod 0600 ~/.ssh/id_ed25519
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - git clone git@github.com:mtaylor91/argocd-deployment.git
  - cd argocd-deployment
  - ./bin/update-repo-tag.sh home/namespaced/mtaylor-io mtaylor.io $DRONE_TAG
  - git commit -a -m "Update mtaylor-io to $DRONE_TAG"
  - git push origin main
  environment:
    SSH_KEY_BASE64:
      from_secret: ssh_key_base64
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
---
kind: pipeline
type: kubernetes
name: promote
steps:
- name: release
  image: images.home.mtaylor.io/deployer:latest
  commands:
  - set -u
  - git fetch origin 'refs/tags/*:refs/tags/*'
  - git fetch origin $${DRONE_BRANCH}
  - export tag=$(get-release-tag)
  - cd deploy
  - kustomize edit set image images.home.mtaylor.io/mtaylor.io:$${tag}
  - cd ../
  - git commit -a -m v$${tag}
  - git tag $${tag}
  - git push origin $${tag}
trigger:
  event:
  - promote
  target:
  - production
