commonLabels:
  app: mtaylor-io
resources:
- deployment.yml
- service.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: images.home.mtaylor.io/mtaylor.io
  newTag: 0.0.19
