name: "Build"
on:
  push:
    branches:
    - "main"
jobs:
  build:
    name: "Build Source"
    runs-on: "mtaylor-io-runners"
    container:
      image: "docker.io/oven/bun:1"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Build"
      run: |
        bun install
        bun run build
    - name: "Upload dist"
      uses: "actions/upload-artifact@v4"
      with:
        name: "dist"
        path: "dist"
        if-no-files-found: "error"
        retention-days: 0
        include-hidden-files: false
    - name: "Upload node_modules"
      uses: "actions/upload-artifact@v4"
      with:
        name: "node_modules"
        path: "node_modules"
        if-no-files-found: "error"
        retention-days: 0
        include-hidden-files: true
  docker:
    name: "Build Docker Image"
    runs-on: "mtaylor-io-runners"
    needs: "build"
    services:
      docker:
        image: "docker.io/docker:dind-rootless"
        options: "--privileged"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    container:
      image: "ubuntu:latest"
    steps:
    - name: "Setup Docker"
      uses: "docker/setup-buildx-action@v3"
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Download dist"
      uses: "actions/download-artifact@v4"
      with:
        name: "dist"
        path: "dist"
    - name: "Download node_modules"
      uses: "actions/download-artifact@v4"
      with:
        name: "node_modules"
        path: "node_modules"
    - name: "Build Docker Image"
      uses: "docker/build-push-action@v6"
