name: "Build"
on:
  push:
    branches:
    - "main"
jobs:
  build:
    name: "Build"
    runs-on: "k8s-home"
    container:
      image: "docker.io/oven/bun:1"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Build"
      run: |
        bun install
        bun run build
