name: "Build"
on:
  push:
    branches:
    - "main"
jobs:
  build:
    name: "Build"
    runs-on: "mtaylor-io-runners"
    container:
      image: "docker.io/oven/bun:1"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Build"
      run: |
        bun install
        bun run build
    - name: "Upload dist"
      uses: "actions/upload-artifact@v4"
      with:
        name: "dist"
        path: "dist"
        if-no-files-found: "error"
        retention-days: 0
        include-hidden-files: false
    - name: "Upload node_modules"
      uses: "actions/upload-artifact@v4"
      with:
        name: "node_modules"
        path: "node_modules"
        if-no-files-found: "error"
        retention-days: 0
        include-hidden-files: true
