name: "Build"
on:
  push:
    branches:
    - "main"
jobs:
  build:
    name: "Build Source"
    runs-on: "mtaylor-io-runners"
    container:
      image: "docker.io/oven/bun:1"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Build"
      run: |
        bun install
        bun run build
    - name: "Upload dist"
      uses: "actions/upload-artifact@v4"
      with:
        name: "dist"
        path: "dist"
        if-no-files-found: "error"
        retention-days: 0
        include-hidden-files: false
    - name: "Upload node_modules"
      uses: "actions/upload-artifact@v4"
      with:
        name: "node_modules"
        path: "node_modules"
        if-no-files-found: "error"
        retention-days: 0
        include-hidden-files: true
  docker:
    name: "Build Docker Image"
    runs-on: "mtaylor-io-runners"
    needs: "build"
    container:
      image: "gcr.io/kaniko-project/executor:debug"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Download dist"
      uses: "actions/download-artifact@v4"
      with:
        name: "dist"
        path: "dist"
    - name: "Download node_modules"
      uses: "actions/download-artifact@v4"
      with:
        name: "node_modules"
        path: "node_modules"
    - name: "Docker Metadata"
      uses: "docker/metadata-action@v5"
      with:
        images: "images.home.mtaylor.io/mtaylor.io"
        tags: |
          latest
          type=sha
